cloudera/livy

api/src/main/java/com/cloudera/livy/Job.java
api/src/main/java/com/cloudera/livy/JobHandle.java
api/src/main/java/com/cloudera/livy/LivyClient.java
api/src/main/java/com/cloudera/livy/metrics/Metrics.java
api/src/main/java/com/cloudera/livy/metrics/ShuffleReadMetrics.java
api/src/main/java/com/cloudera/livy/metrics/ShuffleWriteMetrics.java
api/src/test/java/com/cloudera/livy/TestClientFactory.java
client-common/pom.xml
client-common/src/main/java/com/cloudera/livy/client/common/BufferUtils.java
client-common/src/main/java/com/cloudera/livy/client/common/Serializer.java
client-common/src/test/java/com/cloudera/livy/client/common/TestSerializer.java
client-local/pom.xml
client-local/src/main/java/com/cloudera/livy/client/local/BaseProtocol.java
client-local/src/main/java/com/cloudera/livy/client/local/JobHandleImpl.java
client-local/src/main/java/com/cloudera/livy/client/local/LocalClient.java
client-local/src/main/java/com/cloudera/livy/client/local/RemoteDriver.java
client-local/src/main/java/com/cloudera/livy/client/local/rpc/KryoMessageCodec.java
client-local/src/main/java/com/cloudera/livy/client/local/rpc/README.md
client-local/src/test/java/com/cloudera/livy/client/local/TestJobHandle.java
client-local/src/test/java/com/cloudera/livy/client/local/TestSparkClient.java
pom.xml

To implement the HTTP-based protocol for the Spark client API, the
Livy server needs to be able to bypass data serialized in the
client to the remote driver, without trying to deserialize it
in the process, because it doesn't have the necessary client
classes to do that.
This change adds a private api in client-local and some shared
helper code to implement this bypass; the remote driver will
deserialize these jobs as part of executing them. The code
running inside the Livy server becomes a dumb bypass for the
job and its result.
- Removed "Serializable" from API, since it only adds noise when
using Kryo.
- Added a "client-common" package with shared serde code to implement
bypass jobs.
- Added "private" API to client-local to send already serialized jobs
to the remote context.

Add support to bypass pre-serialized jobs in client-local.

---

api/src/main/java/com/cloudera/livy/LivyClientBuilder.java
client-local/src/main/java/com/cloudera/livy/client/local/LocalClient.java
server/src/main/scala/com/cloudera/livy/server/SessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/client/ClientSessionServlet.scala
server/src/test/scala/com/cloudera/livy/server/BaseSessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/batch/BatchServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/client/ClientServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionServletSpec.scala
spark/src/main/scala/com/cloudera/livy/spark/client/ClientMessage.scala
spark/src/main/scala/com/cloudera/livy/spark/client/ClientSession.scala
spark/src/main/scala/com/cloudera/livy/spark/client/SessionClientTracker.scala

This is not complete; it allows creating / tearing down sessions and
submitting synchronous / asynchronous jobs, but there's currently no
way to retrieve a job's results (or even monitoring it's state, since
the backend code for that is not implemented).
Also includes a new base test class for the servlets that does away
with a lot of copy & paste.

Add servlet to handle livy client sessions.

---

client-local/src/main/java/com/cloudera/livy/client/local/BaseProtocol.java
client-local/src/main/java/com/cloudera/livy/client/local/BypassJobStatus.java
client-local/src/main/java/com/cloudera/livy/client/local/LocalClient.java
client-local/src/main/java/com/cloudera/livy/client/local/driver/BypassJobWrapper.java
client-local/src/main/java/com/cloudera/livy/client/local/driver/DriverProtocol.java
client-local/src/main/java/com/cloudera/livy/client/local/driver/JobWrapper.java
client-local/src/main/java/com/cloudera/livy/client/local/driver/RemoteDriver.java
client-local/src/test/java/com/cloudera/livy/client/local/TestSparkClient.java
spark/src/main/scala/com/cloudera/livy/spark/client/ClientSession.scala

Right now, bypass jobs work like normal jobs; they return data to the
client as they make progress, and return the results at the end.
When the client in the picture is the Livy server, that's not desirable.
That means that the Livy server would have to store all data generated
by client jobs until the client decide to poll for it; meaning that jobs
could consume lots of memory on the Livy server just by returning a lot
of data.
This change modifies the local client, where the bypass API is implemented,
to store job data in the driver process until it's polled by the client.
This means no data about a job is transferred back to the client until
the client explicitly asks for it. So in Livy's case, instead of a job
consuming memory in the server process, it would do so in the driver …

Modify bypass jobs to use polling to fetch status.

---

core/src/test/scala/com/cloudera/livy/sessions/BaseInteractiveSessionSpec.scala
spark/src/main/scala/com/cloudera/livy/spark/interactive/InteractiveWebSession.scala
spark/src/test/scala/com/cloudera/livy/spark/interactive/InteractiveSessionProcessSpec.scala

The session could be in an error state with the underlying process
still alive; need to explicitly kill the process in that case, so
that it doesn't linger around.

Fix process leak in interactive session test.

---

server/src/main/scala/com/cloudera/livy/server/SessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/client/ClientSessionServlet.scala
server/src/test/scala/com/cloudera/livy/server/client/ClientServletSpec.scala
spark/src/main/scala/com/cloudera/livy/spark/client/ClientMessage.scala
spark/src/main/scala/com/cloudera/livy/spark/client/ClientSession.scala

Use the new APIs in the local-client module to fetch job status and
send results back to the requester. A lot of the changes here are
cleanup so that code doesn't need to be repeated all the time.

Implement client methods to retrieve job status, results.

---

api/src/main/java/com/cloudera/livy/LivyClient.java
api/src/test/java/com/cloudera/livy/TestClientFactory.java
client-common/src/main/java/com/cloudera/livy/client/common/ClientConf.java
client-common/src/test/java/com/cloudera/livy/client/common/TestClientConf.java
client-local/src/main/java/com/cloudera/livy/client/local/LocalClient.java
client-local/src/main/java/com/cloudera/livy/client/local/LocalConf.java
client-local/src/main/java/com/cloudera/livy/client/local/driver/RemoteDriver.java
client-local/src/main/java/com/cloudera/livy/client/local/rpc/SaslHandler.java
client-local/src/test/java/com/cloudera/livy/client/local/TestSparkClient.java
client-local/src/test/java/com/cloudera/livy/client/local/rpc/TestRpc.java
spark/src/main/scala/com/cloudera/livy/spark/client/SessionCache.scala

I'll need something like LocalConf for the HTTP client also, so
break the useful parts into an abstract class and modify LocalConf
to inherit from it; the new class does not inherit from Hadoop's
Configuration, so some code needed to be reimplemented.
Also removed "clientId()" from the public API since that is not
really important for users. At least not now.

Add helper class for config data, clean up unused public API.

---

api/src/main/java/com/cloudera/livy/LivyClientBuilder.java
api/src/test/java/com/cloudera/livy/TestLivyClientBuilder.java
api/src/test/resources/livy-client.conf
api/src/test/resources/spark-defaults.conf
client-http/src/test/scala/com/cloudera/livy/client/http/HttpClientSpec.scala
client-local/src/main/java/com/cloudera/livy/client/local/LocalClient.java
client-local/src/main/java/com/cloudera/livy/client/local/LocalConf.java
client-local/src/main/java/com/cloudera/livy/client/local/driver/RemoteDriver.java
client-local/src/test/java/com/cloudera/livy/client/local/TestSparkClient.java
server/src/test/scala/com/cloudera/livy/server/client/ClientServletSpec.scala
spark/src/main/scala/com/cloudera/livy/spark/client/ClientSession.scala

To make it easier to manage client configurations, allow LivyClientBuilder
to load configuration from files present in the classpath, mimicking what
other Hadoop APIs also do. The class will look for two files (livy-client.conf
and spark-defaults.conf) and load their contents if they're present.
On the server side, the ClientSession implementation was changed to
use this instead of trying to load Spark configuration from the system
properties. This should allow server-specific defaults to be configured
while allowing clients to override individual configs using the
session create request.
In the client-local implementation, I broke Spark and Livy configurations
into two separate files, to (arguably) simplify the code a bit. This is
not strictly related to the client configs change; but I …

Automatically load default configuration from the classpath.

---

client-http/src/test/scala/com/cloudera/livy/client/http/HttpClientSpec.scala
core/pom.xml
core/src/main/scala/com/cloudera/livy/sessions/Kind.scala
core/src/main/scala/com/cloudera/livy/sessions/SessionFactory.scala
core/src/main/scala/com/cloudera/livy/sessions/SessionManager.scala
core/src/test/scala/com/cloudera/livy/sessions/SessionManagerSpec.scala
server/src/main/scala/com/cloudera/livy/server/JsonServlet.scala
server/src/main/scala/com/cloudera/livy/server/SessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/batch/BatchSessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/client/ClientSessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSessionServlet.scala
server/src/test/scala/com/cloudera/livy/server/BaseJsonServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/BaseSessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/JsonServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/batch/BatchServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/client/ClientServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionServletSpec.scala
spark/src/main/scala/com/cloudera/livy/spark/SparkManager.scala
spark/src/main/scala/com/cloudera/livy/spark/batch/BatchSessionFactory.scala
spark/src/main/scala/com/cloudera/livy/spark/client/ClientSessionFactory.scala
spark/src/main/scala/com/cloudera/livy/spark/interactive/InteractiveSessionFactory.scala

I don't like json4s; it makes it hard to work with proper types,
and it doesn't understand Java types. This change replaces Scalatra's
JsonSupport, which is based on json4s, with a new 'JsonServlet', which
is based on Jackson.
The new servlet provides routing methods that give the handlers access
to the deserialized type directly, without the need to interact with
Jackson at all; just define the expected type and the servlet handles
the rest.
A corresponding base test class was added to help with writing tests
for these new methods.
As for the existing code, a few changes had to be made:
- The session class hierarchy had to be modified to take a new
type argument (the Scala/Java type of the request object, so
that SessionServlet can automatically deserialize it). Methods
that depended on …

Replace JsonSupport with a Jackson-based servlet.

---

client-http/src/test/scala/com/cloudera/livy/client/http/HttpClientSpec.scala
conf/livy.conf
integration-test/src/main/scala/com/cloudera/livy/test/framework/BaseIntegrationTestSuite.scala
integration-test/src/main/scala/com/cloudera/livy/test/framework/MiniCluster.scala
integration-test/src/test/scala/com/cloudera/livy/test/BatchIT.scala
integration-test/src/test/scala/com/cloudera/livy/test/InteractiveIT.scala
rsc/src/main/java/com/cloudera/livy/rsc/RSCClient.java
rsc/src/main/java/com/cloudera/livy/rsc/RSCConf.java
rsc/src/main/java/com/cloudera/livy/rsc/driver/RSCDriver.java
server/src/main/scala/com/cloudera/livy/server/batch/BatchSession.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSessionServlet.scala
server/src/main/scala/com/cloudera/livy/utils/SparkApp.scala
server/src/main/scala/com/cloudera/livy/utils/SparkYarnApp.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/utils/SparkYarnAppSpec.scala

- Transit to dead state when the YARN application dies.
- If RSCClient.stop() fails to stop RSCDriver, kill the YARN application using YARN API.
- Expose YARN app id.
- Show YARN diagnosis in session log.
- Fixed flaky SparkYarnAppSpec.should kill yarn app.
- Increased some integration test timeout when running on Travis.

LIVY-186. Better YARN integration for Interactive Session.

---

server/src/main/scala/com/cloudera/livy/server/SessionServlet.scala
server/src/test/scala/com/cloudera/livy/server/SessionServletSpec.scala

getPathInfo may return null if there's no path info, this will lead to wrong `location` data in the returning headers, so here fix this.
To produce this issue:
```python
>>> import json, pprint, requests, textwrap
>>> host = 'http://localhost:8998'
>>> data = {'kind': 'spark'}
>>> headers = {'Content-Type': 'application/json'}
>>> r = requests.post(host + '/sessions', data=json.dumps(data), headers=headers)
>>> r.json()
{u'kind': u'spark', u'log': [], u'proxyUser': None, u'state': u'starting', u'appId': None, u'owner': None, u'id': 0}
>>> r.headers['location']
'null/sessions/0'
```
the right value should be:
```python
>>> r.headers['location']
'/sessions/0'
```

LIVY-209. Fix getPathInfo return null issue

---

integration-test/src/test/scala/com/cloudera/livy/test/JobApiIT.scala
rsc/src/main/java/com/cloudera/livy/rsc/driver/RSCDriverBootstrapper.java

Livy internal configurations will be existed as system properties in Spark driver process, and these can be fetched through various ways in Spark's runtime, so here propose to remove these Livy only system properties after being set to `RSCConf`.

LIVY-161. Avoid exposing livy internal configurations to Spark

---

client-common/src/main/java/com/cloudera/livy/client/common/HttpMessages.java
client-http/src/test/scala/com/cloudera/livy/client/http/HttpClientSpec.scala
integration-test/src/test/scala/com/cloudera/livy/test/BatchIT.scala
integration-test/src/test/scala/com/cloudera/livy/test/InteractiveIT.scala
server/src/main/scala/com/cloudera/livy/server/batch/BatchSession.scala
server/src/main/scala/com/cloudera/livy/server/batch/BatchSessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSessionServlet.scala
server/src/main/scala/com/cloudera/livy/sessions/Session.scala
server/src/main/scala/com/cloudera/livy/utils/SparkApp.scala
server/src/main/scala/com/cloudera/livy/utils/SparkYarnApp.scala
server/src/test/scala/com/cloudera/livy/server/batch/BatchServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/batch/BatchSessionSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala
server/src/test/scala/com/cloudera/livy/utils/SparkYarnAppSpec.scala

They are exposed as:
- appInfo.driverLogUrl
- appInfo.sparkUiUrl

LIVY-208. Exposing YARN driver log url and Spark UI url for YARN sessions.

---

.gitignore

Update gitignore file to exclude egg files generated by python api module.

Minor. Update gitignore to ignore egg files

---

server/src/main/scala/com/cloudera/livy/utils/SparkApp.scala

The user defined tags will be merged into generated tags. The key is not used correctly.

Minor. Fixed bug in SparkApp that merges user YARN tags and Livy YARN tags incorrectly.

---

client-http/pom.xml
client-http/src/test/scala/com/cloudera/livy/client/http/HttpClientSpec.scala
core/pom.xml
core/src/test/scala/com/cloudera/livy/LivyBaseUnitTestSuite.scala
core/src/test/scala/com/cloudera/livy/LivyTestFixture.scala
repl/pom.xml
repl/src/test/scala/com/cloudera/livy/repl/BaseInterpreterSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/BaseSessionSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/ReplDriverSuite.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRInterpreterSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRSessionSpec.scala
scala-api/pom.xml
scala-api/src/test/scala/com/cloudera/livy/scalaapi/ScalaClientTest.scala
scala-api/src/test/scala/com/cloudera/livy/scalaapi/ScalaClientTestUtils.scala
scala-api/src/test/scala/com/cloudera/livy/scalaapi/ScalaJobHandleTest.scala
server/pom.xml
server/src/test/scala/com/cloudera/livy/server/ApiVersioningSupportSpec.scala
server/src/test/scala/com/cloudera/livy/server/BaseJsonServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/LivyServerSuite.scala
server/src/test/scala/com/cloudera/livy/server/batch/BatchSessionSpec.scala
server/src/test/scala/com/cloudera/livy/server/batch/CreateBatchRequestSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/CreateInteractiveRequestSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/StatementSpec.scala
server/src/test/scala/com/cloudera/livy/sessions/SessionManagerSpec.scala
server/src/test/scala/com/cloudera/livy/sessions/SessionSpec.scala
server/src/test/scala/com/cloudera/livy/utils/SparkYarnAppSpec.scala

Propose to add unit test context info before and after each unit test, so unit test log can be distinguished from test to test, here is the sample output:
```
==== TEST OUTPUT FOR com.cloudera.livy.repl.SparkSessionSpec: 'should start in the starting or idle state' ====
16/09/09 10:59:15.735 pool-17-thread-1 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/09/09 10:59:15.871 pool-17-thread-1 INFO SecurityManager: Changing view acls to: sshao
16/09/09 10:59:15.872 pool-17-thread-1 INFO SecurityManager: Changing modify acls to: sshao
16/09/09 10:59:15.873 pool-17-thread-1 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(sshao); users with modify …
```

LIVY-210. Add test context for Livy unit test

---

integration-test/src/main/scala/com/cloudera/livy/test/framework/BaseIntegrationTestSuite.scala
integration-test/src/test/scala/com/cloudera/livy/test/InteractiveIT.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala

Should use `spark.executor.instances` instead.

LIVY-216. Fix wrong executor number configuration in interactive session.

---

server/src/main/scala/com/cloudera/livy/utils/SparkProcessBuilder.scala

Removed default value for name parameter for batch.

LIVY-221. Default Livy name is overwriting spark.app.name.

---

pom.xml
server/pom.xml

- Default to compile.
- Users who want to exclude Hadoop jars in their Livy build can set it to provided.

Added an override for hadoop.scope to Hadoop dependencies in pom.xml.

---

pom.xml

To mitigate the difference between building against Spark 1 and 2, propose to upgrade Netty to 4.0.29.Final.

LIVY-226. Upgrade Netty version

---

server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala

This PR is to detect datanucleus jars for spark 2.x where datanucleus is in different locations compared to spark 1.x.
Manually tested.

LIVY-224. Datanucleus jars are not detected for spark 2.x

---

server/src/main/scala/com/cloudera/livy/utils/LivySparkUtils.scala
server/src/test/scala/com/cloudera/livy/utils/LivySparkUtilsSuite.scala

Fixed Spark version regex to support version like 2.0.0.2.5.1.0-56.

LIVY-229. Spark version check fails when it's used with HDP built Spark.

---

server/src/main/scala/com/cloudera/livy/utils/SparkProcessBuilder.scala

The livy code takes the pyFiles variable and passes it as a --conf "spark.submit.pyFiles=<whatever>" as a command line to spark.
The spark.submit.pyFiles was only introduced in spark 2.0.X and is not availablw in 1.6.X
I tried to run it with spark 2.0.1 but it turns out that spark 2.0.X has also a bug(!!!) that ignores this option lolol....
This change make it being passed as --py-files instead...
This is critical for pyspark users as it solves a bug that makes livy useless for pyspark developers.

LIVY-220. Workaround SPARK-17512 for Spark 2.

---

assembly/assembly.xml
assembly/pom.xml
integration-test/pom.xml
server/src/main/scala/com/cloudera/livy/LivyConf.scala
server/src/main/scala/com/cloudera/livy/server/LivyServer.scala
server/src/main/scala/com/cloudera/livy/server/interactive/CreateInteractiveRequest.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/main/scala/com/cloudera/livy/utils/LivySparkUtils.scala
server/src/test/scala/com/cloudera/livy/server/interactive/BaseInteractiveServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala
server/src/test/scala/com/cloudera/livy/utils/LivySparkUtilsSuite.scala

With this change, Livy's assembly package will have two REPL bundles: `repl_2.10-jars` and `repl_2.11-jars`. Livy will pick the right jars based on:
1. If Scala version can be detected automatically by Livy.
2. If User specify Scala major version in `CreateInteractiveSession`.
3. If Livy could figure out default Scala version for Spark.
Please review and suggest, thanks a lot.
CC @tc0312 .

LIVY-227. Include both repl-2.10 and repl-2.11 bundles in Livy assembly.

---

client-http/src/test/scala/com/cloudera/livy/client/http/HttpClientSpec.scala
integration-test/src/main/scala/com/cloudera/livy/test/framework/BaseIntegrationTestSuite.scala
integration-test/src/main/scala/com/cloudera/livy/test/framework/LivyRestClient.scala
integration-test/src/test/scala/com/cloudera/livy/test/InteractiveIT.scala
rsc/src/main/java/com/cloudera/livy/rsc/RSCClient.java
server/src/main/scala/com/cloudera/livy/server/LivyServer.scala
server/src/main/scala/com/cloudera/livy/server/SessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/batch/BatchSessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/recovery/ZooKeeperStateStore.scala
server/src/main/scala/com/cloudera/livy/sessions/SessionManager.scala
server/src/test/scala/com/cloudera/livy/server/BaseSessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/SessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/batch/BatchServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/BaseInteractiveServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/JobApiSpec.scala
server/src/test/scala/com/cloudera/livy/sessions/SessionManagerSpec.scala

livy-server can now recover interactive sessions after restart.
There are some special cases:
- If livy-server crashes while an interactive session is starting, there's a chance the session is unrecoverable, depending on timing (whether livy-repl has registered to livy-server).
- If livy-server is down longer than the value of server.idle_timeout (default: 10min), livy-repl will timeout and quit.
Note: All previous statements are lost after recovery. This will be fixed in a different commit.

LIVY-212. Implemented session recovery for interactive session. Only work with YARN.

---

integration-test/src/main/scala/com/cloudera/livy/test/framework/MiniCluster.scala
integration-test/src/test/scala/com/cloudera/livy/test/InteractiveIT.scala

1. Create a dummy jar to let Spark yarn#client correctly launch the application.
2. Since `SQLContext` is deprecated in Spark 2.0, so additional information will be printed out when creating. Changing the regex pattern.

LIVY-225. Fix two issues running integration test with Spark 2.0.

---

.travis.yml
integration-test/minicluster-dependencies/pom.xml
integration-test/minicluster-dependencies/scala-2.10/pom.xml
integration-test/minicluster-dependencies/scala-2.11/pom.xml
integration-test/pom.xml
integration-test/src/main/scala/com/cloudera/livy/test/framework/MiniCluster.scala
integration-test/src/test/scala/com/cloudera/livy/test/InteractiveIT.scala
integration-test/src/test/scala/com/cloudera/livy/test/JobApiIT.scala
pom.xml
server/src/main/scala/com/cloudera/livy/server/LivyServer.scala
server/src/main/scala/com/cloudera/livy/utils/LivySparkUtils.scala
server/src/test/scala/com/cloudera/livy/utils/LivySparkUtilsSuite.scala

- Added Maven submodules (minicluster-dependencies) to write Spark classpath of different Scala version to files for MiniCluster.
- Writing classpath to a file instead of Maven properties to maintain ability to run integration tests from IDEs.
- MiniCluster picks and reads the correct Spark classpath and pass it to MiniLivy via spark-default.conf.
- Dependency changes to make sure both repl is built when Maven runs integration-test.
- Verify "ensure Livy internal configurations are not exposed" in InteractiveIT instead of JobsApiIT to avoid job incompatibility issue between Scala 2.10 and 2.11.
- Changed Maven pom.xml to start integration tests in 2.10 and 2.11.
- MiniCluster sets env. var. to tell LivyServer what Spark Scala version it should use.
- Changed Travis to launch 2 builds for …

LIVY-219. Support Scala-2.11 integration test for Livy IT.

---

examples/pom.xml
pom.xml
scala-api/pom.xml
scala-api/scala-2.10/pom.xml
scala-api/scala-2.11/pom.xml

Separate livy-scala-api build to scala-2.10 and scala-2.11, which will make job api support Scala 2.11 build of Spark.

LIVY-234. Support Scala 2.11 for Livy Scala api

---

client-http/src/main/java/com/cloudera/livy/client/http/JobHandleImpl.java
integration-test/src/test/scala/com/cloudera/livy/test/JobApiIT.scala
test-lib/src/main/java/com/cloudera/livy/test/jobs/VoidJob.java

to reproduce this issue:
```
val job = new Job[Void] {
override def call(jc: JobContext): Void = {
jc.sc().map(xxx).saveAsTextFile(xxx)
null
}
}
val result = waitFor(client2.submit(job))
```
We should also consider return value explicitly set as Void not to throw exception.

LIVY-236. Fix NPE issue in Job API when return value is Void

---

rsc/src/main/java/com/cloudera/livy/rsc/ContextLauncher.java

- Disabled JaCoCo for `InteractiveIT.should kill RSCDriver if it doesn't respond to end session`. This test doesn't shutdown RSCDriver's JVM gracefully. JaCoCo might generate a corrupted exec dump and cause EOFException.

LIVY-237. Fixed JaCoCo is randomly throwing EOFException on Travis.

---

client-http/src/test/scala/com/cloudera/livy/client/http/HttpClientSpec.scala
server/src/main/scala/com/cloudera/livy/utils/LivySparkUtils.scala
server/src/test/scala/com/cloudera/livy/utils/LivySparkUtilsSuite.scala

With this change, if Spark version detected from `spark-submit` is greater than the specified one, Livy will log warning instead of throwing the exception. Also change the Scala version check with the same way.

LIVY-232. Remove Max Spark version cap in LivyServer

---

server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala

Currently RSC driver URI is gotten when `PingJob` is finished, which means only when SparkContext and other Spark entry point are fully started and job are finished we could get the RSC driver URI. This unnecessarily prolong the intermediate state of recovery metadata, if LivyServer is failed at this time period, it will never talk the RSC application again.
So we should shorten the time to get RSC driver URI ASAP to mitigate the intermediate state of recovery metadata, that will make session recovery more robust.

LIVY-242. Shorten the time to get RSC driver URI

---

server/src/main/scala/com/cloudera/livy/server/recovery/ZooKeeperStateStore.scala
server/src/test/scala/com/cloudera/livy/server/recovery/ZooKeeperStateStoreSpec.scala

Use the retry times value the sleep time value specified in the config
to create the retry policy for the curator client.
Also elevates `retryPolicy` from a local val into a field that can be
used in other places in the same class.
Task-url: https://issues.cloudera.org/browse/LIVY-243

LIVY-243. ZooKeeperStateStore ignores settings for RetryPolicy

---

integration-test/pom.xml
integration-test/src/test/scala/com/cloudera/livy/test/JobApiIT.scala

1. Update the pom to restrict the scope and remove some unnecessary dependencies.
2. Rewrite `ScalaEcho` test with Java one. Because test-lib will be run under Scala 2.10 and 2.11 environments, while it is built against with Scala 2.10, to avoid potential problems, propose to rewrite with Java.

LIVY-219. Follow-up. Some follow-up works for Cross integration test

---

README.rst
repl/src/main/scala/com/cloudera/livy/repl/PythonInterpreter.scala

Also added documentation for pyspark.

LIVY-248. Clean up how PySpark python interpreters are set.

---

pom.xml
server/src/main/scala/com/cloudera/livy/server/WebServer.scala

Straightforward bugfix for access log file.

LIVY-257. access log is not available

---

server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala

Allow application name to be set from "name" parameter and "conf"s

LIVY-259. Name of interactive sessions are not override-able.

---

conf/livy.conf
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/main/scala/com/cloudera/livy/sessions/Session.scala
server/src/test/scala/com/cloudera/livy/server/interactive/BaseInteractiveServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala

Current `livy.repl.jars` cannot automatically pick jars according to different scala interpreter. So here propose one way to address this issue. 
User could list all the dependencies to `livy.repl.jars`, including `livy-repl_2.10` and `livy-repl_2.11`, Livy automatically pick the right jars according to Spark's scala version and scala jar convention.
\cc @tc0312 .

LIVY-250. Change livy.repl.jars to work with different scala interpreter

---

repl/src/main/scala/com/cloudera/livy/repl/Session.scala

traceback could be json list or json object which is misleading. So this PR would not include traceback when it is null. 
Tested manually.

LIVY-271. Fixed repl session to return traceback as a JSON list in error cases.

---

server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala

- InteractiveSessionSpec.should error out the session if the interpreter dies.

Minor. Fixed flaky unit test.

---

repl/src/main/resources/fake_shell.py
repl/src/test/scala/com/cloudera/livy/repl/PythonInterpreterSpec.scala

```
x = [{"name":"a", "value":None}, {"name":"b", "value":2}]
%table x
```
return error `table rows have different types`
if input value is list, tuple. dict type, need to be allow None value.

LIVY-270. %table shouldn't treat None as its own type.

---

repl/scala-2.10/src/main/scala/com/cloudera/livy/repl/SparkInterpreter.scala
repl/scala-2.10/src/test/scala/com/cloudera/livy/repl/SparkInterpreterSpec.scala
repl/scala-2.11/src/test/scala/com/cloudera/livy/repl/SparkInterpreterSpec.scala
repl/src/main/scala/com/cloudera/livy/repl/AbstractSparkInterpreter.scala

- Instead of using regex, parse for internal frames manually.
- Repl in Scala 2.11 cleans internal frames internally. Skip internal frames cleaning.

LIVY-260. repl is stuck in busy state if Scala interpreter returns some specific error.

---

server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala

due to the latency of session state update, we may get `Busy` instead of `Idle`, please see [here](https://travis-ci.org/cloudera/livy/jobs/184456364). So here using `eventually` to fix it.

Minor. Fix flaky test for interactive session state

---

server/src/main/scala/com/cloudera/livy/utils/LivySparkUtils.scala
server/src/test/scala/com/cloudera/livy/utils/LivySparkUtilsSuite.scala

Spark 2.1.0 will be released soon, we should also bump the supported version to 2.1.x.

LIVY-279. Bump supported Spark version to 2.1.x

---

integration-test/src/main/scala/com/cloudera/livy/test/framework/LivyRestClient.scala
integration-test/src/main/scala/com/cloudera/livy/test/framework/MiniCluster.scala
integration-test/src/test/scala/com/cloudera/livy/test/InteractiveIT.scala
server/src/main/scala/com/cloudera/livy/LivyConf.scala
server/src/main/scala/com/cloudera/livy/server/interactive/CreateInteractiveRequest.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSessionServlet.scala
server/src/main/scala/com/cloudera/livy/server/interactive/SessionHeartbeat.scala
server/src/main/scala/com/cloudera/livy/sessions/SessionManager.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/SessionHeartbeatSpec.scala

Notebook applications like Jupyter might crash while livy is running. No one will clean up its corresponding Livy session and will be leaked.
Heartbeat is added to address this. To keep a session alive, the notebook application must continously make GET requests to the interactive session. If no GET request is made within the heartbeat interval, livy-server will delete the session regardless to its state (busy, idle).
Heartbeat is per session and is controlled by session property "heartbeatTimeoutInSecond". Its default is 0 and it means heartbeat is disabled. To enable heartbeat, please create the session with non-zero "heartbeatTimeoutInSecond" in the create request.

LIVY-165. Added session heartbeat to help notebooks to prevent leakage.

---

repl/src/main/resources/fake_shell.py
repl/src/main/scala/com/cloudera/livy/repl/ProcessInterpreter.scala

Due to the bug introduced in LIVY-233, pyspark interpreter will be failed to start in Spark 1.x, in which `SparkSession` is not supported. So here fix this problem.

LIVY-282. Fix fake_shell unexpectedly exit problem

---

rsc/src/main/java/com/cloudera/livy/rsc/ContextLauncher.java
rsc/src/main/java/com/cloudera/livy/rsc/RSCClient.java

If `ContextLauncher#startDriver` doesn't start correctly, it will trigger the listener with `child` be empty, this will introduce NPE, so here check whether `child` is null or not. Also expose the state of `RSCClient`.
This is originated by @mridulm , please review. \cc @zjffdu .

LIYV-289. Fix NPE in ContextLauncher and expose state of RSCClient

---

conf/livy.conf
server/src/main/scala/com/cloudera/livy/LivyConf.scala
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/test/scala/com/cloudera/livy/server/interactive/BaseInteractiveServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala

The issue is coming from [here](https://groups.google.com/a/cloudera.org/forum/#!topic/livy-dev/KTbBOZ3W3tQ).
Currently `livy.rsc.jars` is a RSC configuration, which means user should specify this configuration each time when creating a session, this is semantically incorrect and inconvenient, also equivalent to `livy.repl.jars`, we should change this to Livy configuration.
Besides current doc uses `livy.jars` as a configuration name, no code honors this configuration name, this should also be updated.

LIVY-295. Make livy.rsc.jars a Livy conf

---

repl/src/main/resources/fake_shell.py
repl/src/main/scala/com/cloudera/livy/repl/PythonInterpreter.scala

HiveContext is always created no matter whether we enable hiveContext through `spark.repl.enableHiveContext`. The root cause is that we depends on `shell.py` of spark. and unformatenlly HiveContext would not initialize itself when created, but defer its initialization until any methods is called. This PR would call `sqlContext.tables()` to check whether hiveContext can work properly.
Tested manully

LIVY-294. HiveContext is always created instead of SQLContext for pyspark

---

conf/livy.conf
server/src/main/scala/com/cloudera/livy/LivyConf.scala
server/src/main/scala/com/cloudera/livy/server/LivyServer.scala
server/src/main/scala/com/cloudera/livy/utils/SparkYarnApp.scala

* Add a new daemon thread to kill leaked livy session regularly.  
* Change the default look-up timeout to 60s.

LIVY-280. Livy session leakage issue when app submission timeout

---

repl/src/main/scala/com/cloudera/livy/repl/SparkRInterpreter.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRInterpreterSpec.scala

Otherwise the expression cannot be properly unescaped. See issuein LIVY-297.

LIVY-297. Code should be escaped again in R interpreter

---

examples/src/main/java/com/cloudera/livy/examples/PiApp.java
examples/src/main/python/pi_app.py
repl/src/main/scala/com/cloudera/livy/repl/BypassPySparkJob.scala
repl/src/main/scala/com/cloudera/livy/repl/PythonInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/ReplDriver.scala

Add two Java / Python Job API examples to Livy to demonstrate how to use.
Also Fix an issue of Python Job API where interpreter is not created when Job request is received in RSCDriver, this will lead to kryo deserialization error.

LIVY-292. Fix Python Job API issue and add Java/python Job API example

---

rsc/src/main/java/com/cloudera/livy/rsc/rpc/Rpc.java
rsc/src/test/java/com/cloudera/livy/rsc/rpc/TestRpc.java

In `Rpc.call()`, RPC function call messages are enqueued to the send buffer of the Channel on `Channel.write()` call because it's called outside of the netty Channel IO event loop.
RPC replies are handled by `RpcDispatcher.channelRead0`. It calls `RpcDispatcher.writeMessage()` which calls `Channel.write()` to send RPC reply messages to the Channel. `RpcDispatcher.channelRead0` is executed in the event loop which means `Channel.write()` writes messages directly to the socket and bypassing the send buffer.
When one side of the RPC channel is making a RPC call but at the same time received another RPC call from the other side. Then this race condition might happen:
- Send call header
- Send reply header
- Send reply payload
- Send call payload
This means RPC reply messages might preempt the …

LIVY-300. Fixed a race condition in rsc's RPC channel.

---

server/src/main/scala/com/cloudera/livy/utils/LivySparkUtils.scala
server/src/test/scala/com/cloudera/livy/utils/LivySparkUtilsSuite.scala

add spark version check case : spark version is 2.0.3-SNAPSHOT

LIVY-302 - Fail to parse Spark version when including "-SNAPSHOT"

---

README.rst

The original code does not run at all (tested in ipython 2.7.3).  The fixed code works great. Overall the README.md for livy is of quite high quality: I am looking forward to working with this project.

Minor. Remove backslash textwrap.dedent heredoc breaks python interpreter

---

integration-test/src/main/scala/com/cloudera/livy/test/framework/MiniCluster.scala

I am integrating livy MiniCluster to zeppelin to do integration test. So I am not using real cluster, the following assert will fail for me if it is outside the if block. In this PR, I move it into if block
```
assert(classPathFile.isFile,
s"Cannot read MiniCluster classpath file: ${classPathFile.getCanonicalPath}")
```

LIVY-311. Set classpath in MiniCluster only when it is not in real cluster

---

.travis.yml
pom.xml
repl/src/main/scala/com/cloudera/livy/repl/SparkContextInitializer.scala

In the current implementation of Livy Spark2 SparkSession, by default hive support will be enabled if not explicitly disabled, this is a default behavior in spark-shell. But in Livy interpreter we will disable it by default, otherwise it will introduce unit test failure.
This is another solution of issue #283 .

LIVY-308. Avoid enabling Hive by default in Spark2

---

README.rst

README incorrectly said `logs` instead of `log` for the `sessions` REST API call, it is correct for the `batches` call below.

MINOR. A small REST API typo in the README

---

server/src/main/scala/com/cloudera/livy/server/recovery/FileSystemStateStore.scala
server/src/test/scala/com/cloudera/livy/server/recovery/FileSystemStateStoreSpec.scala

Currently if the permission of recovery folder is not 700, LivyServer will be down. This is actually not a fatal issue, and sometimes this folder is created by admin who doesn't know this constraint. So instead of throwing exception when permission is not 0700, printing warning log instead.
CC @tc0312

Minor. Relief the constraint of recovery folder permission

---

repl/src/main/scala/com/cloudera/livy/repl/ProcessInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/SparkRInterpreter.scala

`livy.repl.enableHiveContext` doesn't take effect in SparkRInterpreter. Fix it in this PR.
Tested it manually for both spark 1.6 and spark 2.1

LIVY-315. Enable hive in SparkRInterpreter

---

core/pom.xml
core/scala-2.10/pom.xml
core/scala-2.11/pom.xml
pom.xml
repl/src/main/scala/com/cloudera/livy/repl/ProcessInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/ReplDriver.scala
repl/src/main/scala/com/cloudera/livy/repl/SparkRInterpreter.scala
repl/src/test/scala/com/cloudera/livy/repl/PythonInterpreterSpec.scala
scala/pom.xml

Due to support of different Scala versions with same source code, we introduced some parent poms without adding to main pom. This will introduce several issues described in [LIVY-312](https://issues.cloudera.org/browse/LIVY-312). The main issue is that when using Livy API as dependency, maven will be failed to resolve the parent modules.
So here by adding these missing parent poms to main pom to fix this issue. The tricky thing is that we don't want to build this parent pom (this will bring in compilation issue), so inspired by [here](http://stackoverflow.com/questions/1437718/configure-maven-plugins-to-stick-together/1437887#1437887) and [here](http://stackoverflow.com/questions/1501294/maven-skip-parent-project-build), I use the way mentioned to skip compile and test phase for these …

LIVY-312. Fix missing parent poms related issues

---

server/src/main/scala/com/cloudera/livy/sessions/Session.scala
server/src/main/scala/com/cloudera/livy/sessions/SessionManager.scala
server/src/test/scala/com/cloudera/livy/sessions/MockSession.scala

[LIVY-306](https://issues.cloudera.org/projects/LIVY/issues/LIVY-306)
Currently a session timeout can't be configured below 1h. This is due to a hardcoded value that was missed in the clean up of [LIVY-114](https://issues.cloudera.org/browse/LIVY-114) and [LIVY-127](https://issues.cloudera.org/browse/LIVY-127)
Given the minimum was not intended I have simple removed it and the conf value (default of 1h) will always be used.

LIVY-306. Removed hardcoded minimum timeout value

---

python-api/src/test/python/livy-tests/client_test.py

Specified fields for client test. Travis CI looks to be defaulted to python 2.7, so it never came across this issue. 
[LIVY-320](https://issues.cloudera.org/browse/LIVY-320)

LIVY-320. Livy python-api client test failing.

---

conf/livy.conf
core/src/main/scala/com/cloudera/livy/sessions/SessionState.scala
server/src/main/scala/com/cloudera/livy/LivyConf.scala
server/src/main/scala/com/cloudera/livy/sessions/SessionManager.scala
server/src/test/scala/com/cloudera/livy/sessions/SessionManagerSpec.scala

Current session gc mechanism has some issues:
1. Stopped session still needs to wait to timeout to gc-ed.
2. Batch session will be gc-ed unexpectedly in run-time when timing out, which makes long running application impossible.
3. Sometimes user doesn't want to stop idle sessions.
So here with this patch:
1. Never check the activity of batch session, which means batch session will only be gc-ed after stop.
2. Add a configuration to turn off activity check for interactive session, which meets some usage scenarios.
3. Add a configuration to control how long a finished session state will be kept in memory before cleaned out.
CC @tc0312

LIVY-240. Improve the session gc mechanism

---

rsc/src/main/java/com/cloudera/livy/rsc/Utils.java

This happens in unit test, we usually set `livy.rsc.jars` to empty string, and `livy.repl.jars` to `dummy.jar`. And these two configurations will be converted to `spark.jars=,dummy.jar` when submitting application, in Spark side Spark didn't filter out empty string and will be resolved to a dir path in `addJar`, which will lead to exception. So in the Livy side we should also filter out empty string.

Minor. Ignore empty string in configuration join

---

rsc/src/main/java/com/cloudera/livy/rsc/ContextLauncher.java
rsc/src/main/java/com/cloudera/livy/rsc/DriverProcessInfo.java
rsc/src/main/java/com/cloudera/livy/rsc/RSCClient.java
rsc/src/main/java/com/cloudera/livy/rsc/RSCClientFactory.java
server/src/main/scala/com/cloudera/livy/server/interactive/InteractiveSession.scala
server/src/main/scala/com/cloudera/livy/utils/LineBufferedStream.scala
server/src/main/scala/com/cloudera/livy/utils/SparkYarnApp.scala
server/src/test/scala/com/cloudera/livy/utils/SparkYarnAppSpec.scala

Redirect Spark Log to REST Response Log field 
Task Link: https://issues.cloudera.org/browse/LIVY-293

LIVY-293: Redirect Spark Log to REST Response Log field for interactive sessions

---

repl/scala-2.10/src/main/scala/com/cloudera/livy/repl/SparkInterpreter.scala
repl/scala-2.10/src/test/scala/com/cloudera/livy/repl/SparkInterpreterSpec.scala
repl/scala-2.11/src/main/scala/com/cloudera/livy/repl/SparkInterpreter.scala
repl/scala-2.11/src/test/scala/com/cloudera/livy/repl/SparkInterpreterSpec.scala
repl/src/main/scala/com/cloudera/livy/repl/AbstractSparkInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/Interpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/ProcessInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/PythonInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/ReplDriver.scala
repl/src/main/scala/com/cloudera/livy/repl/Session.scala
repl/src/main/scala/com/cloudera/livy/repl/SparkRInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/StatementProgressListener.scala
repl/src/test/scala/com/cloudera/livy/repl/PythonInterpreterSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/PythonSessionSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/ScalaInterpreterSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRInterpreterSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRSessionSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkSessionSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/StatementProgressListenerSpec.scala
rsc/src/main/java/com/cloudera/livy/rsc/RSCConf.java
rsc/src/main/java/com/cloudera/livy/rsc/driver/Statement.java
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionServletSpec.scala
server/src/test/scala/com/cloudera/livy/server/interactive/InteractiveSessionSpec.scala

This proposal adds the support to get the progress of statement by using `SparkListener`. This could potentially Zeppelin like tools to display the progress of submitted statement.

LIVY-272. Support Statement progress for interactive session

---

conf/livy.conf.template
server/src/main/scala/com/cloudera/livy/LivyConf.scala
server/src/main/scala/com/cloudera/livy/server/LivyServer.scala
server/src/main/scala/com/cloudera/livy/server/WebServer.scala

1. Livy server url is exposed as http URL even https is enabled, so we should handle this.
2. Livy server SSL keystore password and key password currently set to same configurations, which should be separated.
Verified locally.

LIVY-329. Fix two SSL issues

---

server/src/test/scala/com/cloudera/livy/sessions/SessionManagerSpec.scala

The fix is inspired by [here](http://stackoverflow.com/questions/11121772/when-i-run-mockito-test-occurs-wrongtypeofreturnvalue-exception).
Tried several times locally without the previous issue, will see if this issue still exist in travis test.

LIVY-331. Fix flaky test (interactive session should not gc-ed if session timeout check is off)

---

core/pom.xml
repl/pom.xml
server/pom.xml

This is mainly used for Zeppelin integration test to start a pseudo livy server.
CC @zjffdu

LIVY-318. Make several modules pushable to the public repo

---

bin/livy-server

[LIVY-249](https://issues.cloudera.org/browse/LIVY-249)
Currently if `livy-server` fails to start it will still return `0` (success), this has been fixed. I also added a `livy-server status` command that will return a status output similar to that of `livy-server start` when it's already running or `livy-server stop` when it's already stopped. Lastly I updated all output text to use `livy-server` instead of `livy_server` since that's the actual name of the script.
Tested manually

LIVY-249. Update livy-server script to include status command and return 1 on error

---

repl/src/main/scala/com/cloudera/livy/repl/ProcessInterpreter.scala
repl/src/main/scala/com/cloudera/livy/repl/SparkRInterpreter.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRInterpreterSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRSessionSpec.scala

- Stopped redirecting stderr to stdout.
- Continue to read ErrorStream (it was only being read once).
- Checking for any errors returned by stderr before returning success.
[LIVY-313](https://issues.cloudera.org/browse/LIVY-313)

LIVY-313. Fixed SparkRInterpreter always returning success.

---

repl/scala-2.10/src/main/scala/com/cloudera/livy/repl/SparkInterpreter.scala
repl/scala-2.11/src/main/scala/com/cloudera/livy/repl/SparkInterpreter.scala

Some Spark packages are depending on scala-reflect 2.11.0 and it conflicts with Spark's scala version 2.11.8.
This's not Livy's fault actually but doesn't hurt to make Livy more fault tolerant.
Since the scala-reflect jar with the correct version must already be in CLASSPATH, fixed livy-repl to not load user supplied scala-reflect jars.

LIVY-323. Fixed livy-repl doesn't start with some spark packages.

---

rsc/src/main/java/com/cloudera/livy/rsc/driver/StatementState.java

This will lead to ClassNotFound issue when running in client mode. Since Spark doesn't have guava dependency.

LIVY-351. Remove the use of guava api in Livy

---

repl/src/test/scala/com/cloudera/livy/repl/SparkRInterpreterSpec.scala
repl/src/test/scala/com/cloudera/livy/repl/SparkRSessionSpec.scala

This is caused by the difference of error output with different versions of R.

LIVY-349. Fix two SparkR test issue regarding to different versions of R

---

server/src/main/scala/com/cloudera/livy/LivyConf.scala
server/src/main/scala/com/cloudera/livy/server/WebServer.scala

This patch is based on #266 , mainly to fix header size too large problem in spnego enabled scenario. 
1. Increase the default header size.
2. Make header size configurable.

LIVY-358. Make JettyServer Http request and response header size configurable

---

.travis.yml

The issue is tracked here https://github.com/pypa/setuptools/issues/1042.

Minor. [build-issue] Make sure to install setuptools less then version 36.0.0 to avoid module six not found issue
